build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.11
  amd64: ghcr.io/home-assistant/amd64-base-python:3.11
  armv7: ghcr.io/home-assistant/armv7-base-python:3.11
labels:
  org.opencontainers.image.title: "ToDoTracker"
  org.opencontainers.image.description: "Task manager for Home Assistant"
  org.opencontainers.image.source: "https://github.com/ianso/todotracker"
  org.opencontainers.image.licenses: "MIT"
